[package]
name = "bp_time"
version = "0.2.0"
authors = ["ndts55 <nicolastorres@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
regex = "1.3.6"
lazy_static = "1.4.0"
